export const types = {
  SET_TOKEN: "SET_TOKEN",
  USER_IS_AUTH: "USER:SET_IS_AUTH",
  FETCH_TOKEN: "FETCH_TOKEN",
  FETCH_USER_ID: "USER:FETCH_USER_ID",
  ADD_JOGS: "JOGS:ADD_JOGS",
  SET_JOGS: "JOGS:SET_JOGS",
  EDIT_JOGS: "JOGS:EDIT_JOGS",
}
